---
title: "DS 4420 ML2 Project: Bayesian Model"
author: "Ayush Desai and Kaydence Lin"
output: html_document
date: "2026-04-15"
---

```{r}
library(brms)
library(tidyverse)
library(caret)
```

Load Data
```{r}
airbnb <- read.csv("../data/airbnb_clean.csv") |>
  mutate(
    borough = factor(neighbourhood_group_cleansed),
    room_type = factor(room_type)
  )
head(airbnb)
```

```{r}
normal_prior <- c(
  prior(normal(0, 1), class = b),
  prior(normal(0, 2.5), class = Intercept)
)

airbnb_brm_normal <- brm(ghost_label ~ 
                      availability_365 + minimum_nights + host_has_profile_pic + 
                      host_identity_verified + host_listings_count + 
                      days_since_last_review + reviews_per_month + price,                       
                      family = bernoulli("logit"),  
                      data = airbnb,
                      chains = 4,
                      iter = 2000,
                      warmup = 1000,
                      prior = normal_prior)  
```

```{r}
summary(airbnb_brm_normal)
```

```{r}
plot(airbnb_brm_normal)
```

Posterior predictive distribution
```{r}
post_preds <- posterior_predict(airbnb_brm_normal)
head(post_preds[,1:10])
```

```{r}
ghost_post_preds <- post_preds[,1]
hist(ghost_post_preds)
mean(ghost_post_preds)
airbnb$ghost_label[1]
```

```{r}
post_draws <- as.data.frame(airbnb_brm_normal)

sigmoid <- function(w, x){
  1/(1 + exp(-t(w)%*%x))
}

listing_x <- as.matrix(c(1, unlist(airbnb[1, c("availability_365", "minimum_nights", 
                                                 "host_has_profile_pic", "host_identity_verified",
                                                 "host_listings_count", "days_since_last_review",
                                                 "reviews_per_month", "price")])), ncol = 1)

post_sigmoids <- c()
for(i in 1:nrow(post_draws)){
  w_tilde <- matrix(unlist(post_draws[i, 1:9]), ncol = 1)  
  post_sigmoids <- c(post_sigmoids, sigmoid(w_tilde, listing_x))
}

hist(post_sigmoids, main = "Posterior Probability: Listing 1 is a Ghost",
     xlab = "Probability")
mean(post_sigmoids)
airbnb$ghost_label[1]

```

```{r}
# Effect of individual predictors
plot(conditional_effects(airbnb_brm_normal, "availability_365"))
plot(conditional_effects(airbnb_brm_normal, "minimum_nights"))
plot(conditional_effects(airbnb_brm_normal, "host_has_profile_pic"))
plot(conditional_effects(airbnb_brm_normal, "host_identity_verified"))
plot(conditional_effects(airbnb_brm_normal, "host_listings_count"))
plot(conditional_effects(airbnb_brm_normal, "days_since_last_review"))
plot(conditional_effects(airbnb_brm_normal, "reviews_per_month"))
plot(conditional_effects(airbnb_brm_normal, "price"))
```


```{r}
complete_rows <- complete.cases(airbnb[, c("ghost_label", "availability_365", "minimum_nights",
                                           "host_has_profile_pic", "host_identity_verified",
                                           "host_listings_count", "days_since_last_review",
                                           "reviews_per_month", "price")])

airbnb_clean <- airbnb[complete_rows, ]

pred_probs <- posterior_epred(airbnb_brm_normal) |> colMeans()
pred_labels <- ifelse(pred_probs > 0.5, 1, 0)
actual <- airbnb_clean$ghost_label

cat("pred_labels length:", length(pred_labels), "\n")
cat("actual length:", length(actual), "\n")

conf_mat <- confusionMatrix(factor(pred_labels), factor(actual), positive = "1")
print(conf_mat)

accuracy  <- conf_mat$overall["Accuracy"]
precision <- conf_mat$byClass["Precision"]
recall    <- conf_mat$byClass["Recall"]
f1        <- conf_mat$byClass["F1"]
```

```{r}
bayes_R2(airbnb_brm_normal)
```




